[versions]
agp = "8.6.0"
kotlin = "1.9.0"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
bluetooth = "1.0.0-alpha02"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version = "1.7.0" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version = "1.4.0" }
material = { group = "com.google.android.material", name = "material", version = "1.4.0" }
junit = { group = "junit", name = "junit", version = "4.13.2" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version = "1.1.3" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version = "3.4.0" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version = "1.3.1" }
androidx-bluetooth = { group = "androidx.bluetooth", name = "bluetooth", version.ref = "bluetooth" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

